### PR TITLE
Stack builder2

### PR DESCRIPTION
**Pull request by hogoww**
weird previous PR.
Fixed the StackBuilder & tests, added necessary comments (still missing some)

### CODE REVIEW

**Comment by hogoww** [comment]
Memory tests are failling.
Everything else's good.


        self createStackPage.
	previousFrame ifNotNil:[ ^ self ].
	page := interpreter stackPages newStackPage.
	pointer := page baseAddress.
	interpreter stackPointer: pointer + memory wordSize.
	
-------		
	interpreter push: receiver.
	args do: [ :anArg | interpreter push: anArg ].
	interpreter push: senderContext.
	"base frame's saved fp is null"
	memory coInterpreter push: 0.
--------
	page
		baseFP: interpreter stackPointer;
		headFP: interpreter stackPointer.
	interpreter push: method.


difference with in the previous version, (which works for memory tests)

**Comment by guillep** [comment]
Hi Pierre,

If memory tests are failing we cannot integrate this. That means the PR should not have touched existing tests (unless keeping the same behaviour). Or, fixing the tests to handle the new behavior.

**Comment by hogoww** [comment]
Obviously.
This was me documenting for myself for the next time I pick this up.
I've been removing possibilities since we last spoke about this.

**Comment by guillep** [comment]
Maybe we could integrate the stack builder without those changes and integrate the modifications to the tests in a second PR? That would allow us to use the stack builder in fresh tests :)

**Comment by hogoww** [comment]
I was worried that the memory tests were showing that there is a problem with the stack builder.
But I cannot find it, so...
Done.

There is also 3 contexts tests passing to move in the correct test class, & one failling (the one we stopped on last time).

**Pull request merged**
