### PR TITLE
Added comments and renamed methods during todays dojo

### PR DESCRIPTION
**Pull request by Mathilde411**
This was dome with @guillep @tesonep @PalumboN @jordanmontt @hernanmd @Ducasse @Inao0 @jthulhu

### CODE REVIEW

**Comment by jordanmontt** [comment]
There are more changes that the ones that we did. Are those related?

**Comment by Mathilde411** [comment]
Yup that's my fault I selected the wrong branch to merge in, it should have been pharo-12

**Comment by PalumboN** [comment]
Changed ;)

**Review by jordanmontt — APPROVED** [review]

**Comment by guillep** [comment]
Thanks everybody, thanks @BastouP411 !

**Review by guillep — APPROVED** [review]

**Pull request merged**
