### PR TITLE
Manage the case when primitiveGetVMParameter: returns nil

### LINKED ISSUE #12127: [CI]  With latest VM: Segmentation fault when running all tests
**Bug description**
Every second CI rum (that is, when it uses the -lastest vm) leads to a Segmentation fault on all three platforms. See e.g.

https://ci.inria.fr/pharo-ci-jenkins2/blue/organizations/jenkins/Test%20pending%20pull%20request%20and%20branch%20Pipeline/detail/PR-12069/3/pipeline

### PR DESCRIPTION
**Pull request by guillep**
This should

Fix https://github.com/pharo-project/pharo/issues/12127

### CODE REVIEW

**Comment by privat** [comment]
Since the CI did not complain on #518, maybe add some regression tests?

**Comment by guillep** [comment]
Actually, the CI failed consistently in #518, but it got integrated eagerly.

imagen

**Comment by privat** [comment]
Ahah. OK then :)

**Comment by tesonep** [comment]
@guillep There are some tests about ephemerons, is it possible that these methods are from another PR?

**Comment by guillep** [comment]
Yes, let me deal with this

**Pull request merged**
