### PR TITLE
Slang: Integer>>#bitOr: and Integer>>#| are translated to C code differently

### LINKED ISSUE #446: Slang: `Integer>>#bitOr:` and `Integer>>#|` are translated to C code differently
From `Integer>>#bitOr:`:

```
| anInteger
	^self bitOr: anInteger
```

However, when translating it to C code, `Integer>>#bitOr:` is translated to `|` (bitwise or), while `Integer>>#|` is translated to `||` (logical or).

We should translate them both to bitwise or.

Note: we should check if we have the same issue with `bitAnd:` and `&`.

### PR DESCRIPTION
**Pull request by hernanmd**
Fix #446

### CODE REVIEW

**Comment by tesonep** [comment]
@hernanmd There are changes in files that are not related with the issue: the cmake files. Are they part of another PR?

**Comment by hernanmd** [comment]
> 

During the VM Dojo we had problems compiling the VM because SDL2 wasn't build since it was installed in a different location. So we add DEPENDENCIES_FORCE_BUILD option. Let me know if I should open a new issue.

**Comment by guillep** [comment]
> > 
> 
> During the VM Dojo we had problems compiling the VM because SDL2 wasn't build since it was installed in a different location. So we add DEPENDENCIES_FORCE_BUILD option. Let me know if I should open a new issue.

Yes, but that is already in https://github.com/pharo-project/pharo-vm/pull/522, we should rebase this branch and remove the extra commit maybe.

**Comment by privat** [comment]
What a menial task! Good job!

**Comment by hernanmd** [comment]
> > > 
> > 
> > 
> > During the VM Dojo we had problems compiling the VM because SDL2 wasn't build since it was installed in a different location. So we add DEPENDENCIES_FORCE_BUILD option. Let me know if I should open a new issue.
> 
> Yes, but that is already in #522, we should rebase this branch and remove the extra commit maybe.

I merged the changes and now the included commits are only related to this issue: https://github.com/pharo-project/pharo-vm/pull/523/files


<blockquote><div> GitHub</div><div><strong><a href="https://github.com/pharo-project/pharo-vm/pull/523">Slang: Integer>>#bitOr: and Integer>>#| are translated to C code differently by hernanmd · Pull Request #523 · pharo-project/pharo-vm</a></strong></div><div>Fix #446</div></blockquote>

**Review by guillep — APPROVED** [review]
Changes look good to me.
I restarted the CI

**Comment by guillep** [comment]
CI was good!!!

**Pull request merged**
