### PR TITLE
Refactors related to #primitiveAt

### PR DESCRIPTION
**Pull request by PalumboN**
Some refactors related to `primitiveAt` Druid compilation. 

See: https://gitlab.inria.fr/RMOD/druid/-/merge_requests/6

### CODE REVIEW

**Review by guillep — APPROVED** [review]
Looks ok, I like removing duplicated code :)

I say yes, and delegate the decision to the CI and the tests

**Comment by PalumboN** [comment]
Let's see, but I think that `druid` branch is broken. I opened an issue for that: https://gitlab.inria.fr/RMOD/druid/-/issues/50

**Comment by guillep** [comment]
Yes, 99(+?) unit tests broken

imagen

All seem to be because of the same:

```
Error
primitive #oldIntegerAt:put:size:signed: in ByteArray failed
Salida
PrimitiveFailed
primitive #oldIntegerAt:put:size:signed: in ByteArray failed
ByteArray(ProtoObject)>>primitiveFailed:
ByteArray(ProtoObject)>>primitiveFailed
ByteArray>>oldIntegerAt:put:size:signed:
OldFFIBackend>>integerOfObject:at:put:size:signed:
ByteArray>>integerAt:put:size:signed:
SlangMemoryRegion>>integerAt:put:size:signed:
```

**Comment by PalumboN** [comment]
We should update the branch with `pharo9` (or `pharoX`?) changes. They have all tests green and CI pass _almost_ all stages.

**Comment by guillep** [comment]
Yes, we can do that

**Comment by guillep** [comment]
I merged in `pharoX` in `druid`, rerunning the CI

**Pull request merged**
