### PR TITLE
Cleanups/externalize internalize

### PR DESCRIPTION
**Pull request by guillep**
Many cleanups, mainly removing duplicated code

### CODE REVIEW

**Comment by astares** [comment]
why is this PR against "Pharo 10" branch, not 11 or 12?

**Review by PalumboN — APPROVED** [review]
Nice work!! 👏 

#### There are failing tests yet ❌

**Comment by guillep** [comment]
> Nice work!! 👏
> #### There are failing tests yet ❌

policeman

**Comment by guillep** [comment]
This is getting very green

imagen


Failing tests are because I updated some tests for the latest image, but the latest image is only used in the druid branch.

**Comment by guillep** [comment]
ci is green !

**Pull request merged**
