### PR TITLE
We need to use a fixed version of LibFFI

### PR DESCRIPTION
**Pull request by tesonep**

### CODE REVIEW

**Comment by guillep** [comment]
@hogoww any reason why there are mutant commits in here? 
imagen

**Comment by hogoww** [comment]
Absolutely none, myappologies...

**Comment by guillep** [comment]
> Absolutely none, myappologies...

No problem!

Also, I just realised those commits are not pushed into this branch, they are just references. So no harm done!

Sorry for the noise!

**Comment by guillep** [comment]
Tests are running, many FFI tests are failing:

imagen

Not clear if related.

**Pull request closed without merging**
