### PR TITLE
Add image version field in Image Header and as a Parameter

### PR DESCRIPTION
**Pull request by tesonep**
- Adding Image version to the header
- Adding primitives to access it as VMParameter 79
- Reading / Saving it on image Read / Save

### CODE REVIEW

**Review by guillep — APPROVED** [review]
Only 16 bits? What if I want more versions?

**Comment by guillep** [comment]
Good!

**Comment by tesonep** [comment]
> Only 16 bits? What if I want more versions?

It was a free field that we have in free in older versions at least Pharo 7 & 8, so it can be used to identify the version as the rest will be 0. There was the screen size, but that one we were using it until Pharo 9 (actually we were putting a value in P10 also... but never used).

**Comment by guillep** [comment]
I was joking

**Comment by tesonep** [comment]
> I was joking

When Pharo 6600 will be released, they will remember me....

**Comment by guillep** [comment]
Y2k all over again

**Pull request merged**
