### PR TITLE
Headless refactor parameter handling, OS X DnD

### PR DESCRIPTION
**Pull request by ronsaldo**
This commit performs a refactor on the parameter parsing logic in terms of code convention, correctness and separating completely the logic of opening a dialog from parameter parsing.

This commits ports back opensmalltalk-vm the following features:
- The path handling utility methods.
- The hack for supporting image drag and drop onto the **Pharo.app** on OS X.
- The logic for finding multiple images from **pharo** vm directory, so if there are multiple images that can be choosen from, an open-file dialog can be opened by the VM launcher logic.

On Windows this uses the WIN32 cmake application type for the non-console version. The console version on Windows never opens the open-file dialog and behaves identically to the linux version.

### CODE REVIEW

**Comment by ronsaldo** [comment]
Tests errors are from the FFI. They are not related to this PR.

**Comment by tesonep** [comment]
Hi Ronie,
   we have checked the PR but this is a big one and has many things.
This PR is not possible to be integrated as it is so big and has many
changes at once, and we have comments on them.

We have seen 6 different points in the same PR:

1. Parameter parsing
2. Forced Image name
3. Image lookup
4. Plist
5. Multiple Mains
6. Code Conventions

Having so many things in a PR makes it super difficult to review it.

1. Why the getopts solution is not enough? What are the requirements
it does not help you to implement?
We saw you (re)implemented parameter parsing all by hand and it will
be good to understand what is the rationale behind it.
If you explain it better we can get the idea of it. Without
understanding its rationale it only complexifies the codebase, and we
are exactly looking for the opposite.

1. We do not understand why adding an extra default image name. This
is only adding more complexity without a clear requirement for the
Pharo VM.

2. Why implementing such a complex lookup mechanism for the image?
Which is the requirement for Pharo? The idea we have is that if you
require to implement such a mechanism for a particular application you
can define your own main (or much more code) and pass the resolved
image name as the first argument of the function initPharoVM. That was
the idea to have this function inside an independent DLL.
2.1 Maybe the problem is that the VM should expose more extension
points or something should be split to allow reuse from different
clients?

4. This is fine. We see the requirement for this. Of course, it will
be easier to integrate if it is independent. Now, we cannot integrate
it as is.

5. We don't see the need or the benefits of having duplicated code by
platform when it can be managed with the same code and particular
functions for each platform.

5.1. The Exec in the OSX main looks at least suspicious.
5.2. Together with this, why the file dialog functions have been
inlined in the main files? This, of course, prevents the reusing the
same functions. The original idea was to have a single main for all of
them and special functions for each platform.

6. This is more a cross-cutting concern, that we should discuss with
time. We saw that you added prefixes to some functions and not to
others. Also, some of the functions you rewrote/added have now mixing
casing (snake and camel case) in the same signature. We agree that
having a prefix for the functions is probably nice, even more thinking
about an embeddable  VM. However, we would like a shorter prefix and
only required for the public API functions.
The same idea about casing, we should agree on something.  The code
generated by VM Maker already uses camel case convention, so why not
keeping that?
Finally, there are some inconsistencies in the handling of spaces vs
tabs. This problem already exists in the old code, but for the new
code we need to use improve it.

Could you split this PR in multiple smaller ones?
Maybe you like the 6 points we presented or any other organization,
but try to group them by feature.
Also, it would be nice if you make clear what you actually need so we
can up with a good solution that satisfies all of us.

**Comment by ronsaldo** [comment]
Hello Pablo,

My answers for each one of these points are the followings:
1. getopts is not portable and is not supported by MSVC in Windows. On Mingw it is an extension. Also, it is not consistent across platforms on whether - or -- is used a prefix. I do not find complexity on re-implementing behaviors when there is no portable alternative, specially on Windows.
2. This is required for packaging an application for an end user. See https://github.com/pharo-project/opensmalltalk-vm/issues/23
3. One single main function for end users does not work. There is already existent behaviors that end users are expecting from the executable program that needs to be replicated. Drag and dropping an image on the file explorer onto the .exe or .app is one of these behaviors. That complex lookup mechanism is actually a behavior expected by end users on Windows and OS X. One non-portable size does not fit all, and the envp is not even a part of the C standard (although it is commonly supported).
4. This one is not independent because without the plist it is not even possible to drop the image onto the .app in the OS X Finder.
5. This is about separation of concerns. Those dialogs or anything GUI related do not correspond in the main VM library.
  1. The dropped images onto the .app are passed as events in OS X which requires the creation of the NSApplication singleton and the installation of the NSAppDelegate which is one time operation in the whole application life-cycle. They are not documented APIs for getting this same information, so the only way for getting this data is going through the OS X frameworks which is expected to be created by the image itself, and not the VM. If the execution of the image does not receive a clean operating system environment, unexpected behaviors can happen. For example SDL2 wants to install its own NSAppDelegate for receiving and sending some events. The easiest way to bypass this problem is by using exec which replaces the whole process address space (and keeps the pid, file descriptors, etc), and since this is in the main, this is a safe place for doing it. And also, do not assume that the end user is using a tool such as the PharoLauncher.
  2. This is about separation of concerns. Again, the VM core should not known anything at all about GUIs, which includes file dialogs. The VM core should know at most if it is running in an interactive or non-interactive way. A completely non-interactive headless which should be the default VM core behavior should not be able to create interactive dialogs in any way. Not reusing these functions is not a problem because they should never be reused. Again, the single main for all of the platforms in practice does not work, except for the fully headless case.
6. See https://github.com/pharo-project/opensmalltalk-vm/issues/24 . Sorry, but I cannot work without a proper coding standard. This is discussed now, or I am already forcing a coding standard convention by using it. However, if a proper coding convention is chosen and made public in that discussion that I opened several weeks ago (after a private call between us where I mentioned this as an issue), I can then convert this code and other existent code into the new coding convention. That includes converting eventually the VMMaker code in a separate PR. Having parts of the code being automatically generated is not a valid excuse for neglecting the quality of the manually written C code. I am using at least <namespace>_<restOfTheSymbolName> and <namespace>_<class>_<restOfTheSymbolName>. Symbols that do not follow this kind of convention (which in C is required for avoiding name clashes) should be static, which makes the symbol local to the translation unit. In the previous version of the VM_PARAMETERS (a Windows specific coding convention that looks bad. All UPPER_CASES is normally used for constants and macros) there are also non-clear notions of object ownership which is crucial for managing the lifetime of objects which is prone to memory leaks, memory corruption (e.g. accessing dangling pointers). The tabs and space mixup was already a problem see https://github.com/pharo-project/opensmalltalk-vm/blob/headless/src/winOpenFileDialog.cpp for a weird looking file.

Currently several of these changes are dependent on each other, and we need them all. Some of the changes such as the plist could be easily moved into a separate PR, but since this change is also for enabling the image DnD support into the .app on OS X, then I do not see the need for separating it into a separate PR. And in fact I need some of the changes for making a separate PR with the Win32 resources which I have in these separate branch https://github.com/ronsaldo/opensmalltalk-vm/tree/headless-feature-win32-resources

Sorry, but if I do not see more technical reasons for separating these inter-dependent changes which are all logically grouped into "Parameter parsing, VM initialization, and end user experience improvements on VM launching by a final end user", and a clear public roadmap on how to structure these changes, for now I am not splitting this PR. Since I am doing these changes for a client, for now I am just going to be having to fork the repository.

Best regards,
Ronie

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/pharo-project/opensmalltalk-vm">pharo-project/opensmalltalk-vm</a></strong></div><div>Cross-platform virtual machine for Squeak, Pharo, Cuis, and Newspeak. - pharo-project/opensmalltalk-vm</div></blockquote>
<blockquote><div> GitHub</div><div><strong><a href="https://github.com/ronsaldo/opensmalltalk-vm">ronsaldo/opensmalltalk-vm</a></strong></div><div>Cross-platform virtual machine for Squeak, Pharo, Cuis, and Newspeak. - ronsaldo/opensmalltalk-vm</div></blockquote>

**Comment by ronsaldo** [comment]
This is obsoleted by https://github.com/pharo-project/opensmalltalk-vm/pull/42

**Pull request closed without merging**
