### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by hernanmd**
Updated FIXME references to Wiki pages.

### CODE REVIEW

**Comment by privat** [comment]
Why did you remove the list of packages?

**Comment by hernanmd** [comment]
> Why did you remove the list of packages?

List of packages for Ubuntu were moved to the Wiki page here: https://github.com/pharo-project/pharo-vm/wiki/Compiling-in-Ubuntu
We are trying to simplify README and add links to the wiki for specific instructions.



<blockquote><div> GitHub</div><div><strong><a href="https://github.com/pharo-project/pharo-vm">Compiling in Ubuntu · pharo-project/pharo-vm Wiki</a></strong></div><div>This is the VM used by Pharo. Contribute to pharo-project/pharo-vm development by creating an account on GitHub.</div></blockquote>

**Comment by privat** [comment]
I believe that a README must be sufficient to compile a project from scratch. I advocate that the list of requirement stays in the README.

**Comment by hernanmd** [comment]
> I believe that a README must be sufficient to compile a project from scratch. I advocate that the list of requirement stays in the README.

A README does not necessarily have to be a big manual page that prevents the user from clicking. The setup is only one part of the README, which only those who really want to build the project from scratch will be interested in. As valuable as it is, it is only a use case. A README file in turn should contain general information that can be useful to other people, not just be a big page covering all possible combinations to build the VM from scratch (which could lead to a really long discouraging page). This is well explained [in this video](https://www.youtube.com/watch?v=E6NO0rgFub4) where he talks about "over-explainer" READMEs. 

Linking information to other pages helps users (and editors) not to have to scroll through information that is not of interest to them in search of what they are interested in.

**Comment by MarcusDenker** [comment]
I find it strange that if I do exactly what it says, I do not get a vm that works.

Then I am told that, obviously, I should know about which dependencies are needed or about using some option called PHARO_DEPENDENCIES_PREFER_DOWNLOAD_BINARIES

Is this really so obvious?

**Comment by jordanmontt** [comment]
The wiki looks complete and there is pages explaining how to compile in ubuntu, mangaro, fedora.
I agree that is better to have a not so long README file and that it is better to link to wiki pages, paper, or resources in general.

**Review by jordanmontt — APPROVED** [review]

**Comment by hernanmd** [comment]
@MarcusDenker I will make a pass now because now the page is a mess. It doesn't even have a Table of Contents.

**Pull request merged**
