### PR TITLE
Update SDL

### PR DESCRIPTION
**Pull request by LucFabresse**
updated SDL2 to use official github repo + 2.26.5 release

TODO:
- compile this version 2.26.5 for different arch and push zip on pharo files
- update SDL2 cmake to download those zip

### CODE REVIEW

**Comment by guillep** [comment]
Hi @LucFabresse, Thanks!

I trust you tested this :)

Do I wait for the TODOs or can I proceed with integration?

**Comment by LucFabresse** [comment]
yes tested on my machine (for what it worth) :-)
I guess we should not wait the TODOs to be done. 
It just means that downloaded versions of SDL lib for various architectures will use a different version of SDL until it has been updated on pharo files.
IMO, we should update all architectures to this latest version of SDL but we should test on mac M1/2, raspberry pi, ... maybe just by running it on the CI slaves and force recompiling SDL?

**Comment by guillep** [comment]
We can update slowly the other libs, yes!

**Review by guillep — APPROVED** [review]
Thanks!

**Pull request merged**
