### PR TITLE
Update Jenkins to use Pharo 110 for building

### PR DESCRIPTION
**Pull request by PalumboN**
I'm trying to fix the CI :)

### CODE REVIEW

**Comment by PalumboN** [comment]
The built VM failed while the `PharoTutorialGoOnMockTutorialTest` are running because there is a concurrent access between the test and the UI thread.

We can:
- Ignore the test in the CI
- Or block the UI thread during these tests

**Comment by PalumboN** [comment]
There are also failing tests:

- `CoverageCollectorTest >> testExample`. This test only works in the JITed production VM. We tried using a generated StackVM and the VM generated in this PR and both failed. There is some issue between the CoverageCollector and the VM. **We should rewrite/skip this test**.

- There are two tests from `FLCreateClassSerializationTest` that are failing because of `TestTookTooMuchTime`. **We should mark them as `longTestCase`**.

**Comment by PalumboN** [comment]
Ok, the `testExample` is already fixes in Pharo12

https://github.com/pharo-project/pharo/blob/44816f8b7f27c6397f1a9b0577430f0f3b90f2a7/src/Coverage/CoverageCollectorTest.class.st#L89-L103

I will backport that (and `longTestCase` cases) to Pharo11, so the CI should pass all the Pharo tests after that.

**Comment by guillep** [comment]
Ok, there is no risk at integrating this. It's the right call.
The failing test is in both Pharo11 and 12, as soon as Pharo11 is fixed this will be fixed too.

This avoids the constant failures on JobXXX that were prevalent in Pharo10.
@PalumboN for next time, try that PRs are self-explanatory :P

We should merge this into Pharo12 branch too.

**Comment by PalumboN** [comment]
I cannot image a PR more `self-explanatory` than this:

> I'm trying to fix the CI :)

That was the truth, I did not have more info that 🤣

**Comment by guillep** [comment]
Yes you did!

> This avoids the constant failures on JobXXX that were prevalent in Pharo10.

You told me that Pharo>10 had that test skipped, and that's why you wanted to move!

**Comment by PalumboN** [comment]
Ahh yes! 😅

**Pull request merged**
