### PR TITLE
Simulator refactorings

### PR DESCRIPTION
**Pull request by QDucasse**
Hello, this is the cleanup I made of the different Unicorn simulators. I tried to get as much as possible in the `ProcessorSimulator` class to remove redundant methods. Now, a simulator only has to define the different registers it uses and the access API is already handled in the superclass. A layer of inheritance is added on top of the `UnicornSimulator` class because it might be useful in the case of other simulators (I had to use Spike and reusing the API was handy!).

I will keep this pull request clean from changes that might be needed for Unicorn2 (https://github.com/pharo-project/opensmalltalk-vm/pull/343) and simply encapsulates the refactorings. I pull into `headless` because JIT tests are not passing for `pharo-9`.

### CODE REVIEW

**Comment by guillep** [comment]
> because JIT tests are not passing for pharo-9.

That's strange. They should.
The `headless` branch is not running JIT unit tests I think.
Anyways, maybe we should push this to the pharoX branch instead? @tesonep 

I'll allocate time next week to see why tests do not run

**Comment by QDucasse** [comment]
The `InstructionStream` does not understand `on:pc:` and fails ~180 tests. I believe it should be a simple fix but I have not looked into it

**Comment by guillep** [comment]
I rebased the branch to pharo-9 and changed the base of this PR. Let's wait for the CI.

**Comment by guillep** [comment]
Tests timed out after 20'. I'll check locally

**Comment by guillep** [comment]
Tests are not running in this branch, investigating...

**Comment by guillep** [comment]
The first commit in the branch (b8d554a075d9c798b82daad5b1ff5c7d38c3ed01) introduces seemingly a bug. Going to the previous commit (Pablo's) makes all tests run green.

**Comment by guillep** [comment]
It seems that the method `mapMemoryInManager:` in the main branch has an added line `aMachineSimulatorMemoryManager machineSimulator: self` that is not in the branch that you worked on.
Adding that line fixes the tests.

I wonder why 
 - it was not detected as a merge/rebase conflict
 - how it did not generate a DNU instead of a strange error...

**Comment by guillep** [comment]
Unit tests and most image tests are running!
The broken tests (below) seem not related.

imagen

**Pull request merged**
