### PR TITLE
Dojo primitive compare bytes

### PR DESCRIPTION
**Pull request by PalumboN**
_From the VMDojo with @hernanmd @tesonep @guillep @sbragagnolo @BastouP411 @Inao0 @Ducasse_

Adding a new primitive to compare ByteArrays faster.

There are two implementations, one is using a loop and the other `memcmp`.

## Comparing Performance
- `>1` -> Loop implementation is better 
- `<1` -> memcmp is better.
- x log

image

This chart is telling me that we need both implementations: Loop is 40% faster for small objects, but for sizes > 50 the `memcmp` is at least 2x faster.

And we need a strategy to select the algorithm: because most of the objects in the image are smaller than 12 but there are many that don't (see chart below).

We talked about having a subclass `BigByteArray` overriding the method to use the `memcmp` implementation.

### Objects by size
- x log
- y log

image

-----

Tested on
- Pharo11
- macOS Monterey 12.2.1
- Apple M1
- 16GB RAM

### CODE REVIEW

**Comment by guillep** [comment]
> (Maybe we should remove that before merging? Or at least not publish in the Primitive Table)

yes?

**Comment by PalumboN** [comment]
> > (Maybe we should remove that before merging? Or at least not publish in the Primitive Table)
> 
> yes?

No! I edited the description

**Comment by guillep** [comment]
ok, we need to check this in other hardware then!

**Comment by guillep** [comment]
also, while the distribution of byte arrays is nice, that is not the distribution of the comparison calls. maybe large arrays are compared more often?

what about strings?

**Comment by Ducasse** [comment]
This is why we need better spy libraries :) and the analysis is already cool. 
Keep pushing this.

**Comment by Mathilde411** [comment]
Okay I tested on my machine:
Capture d’écran du 2023-06-07 16-41-28
On my machine the cutoff seems to be appearing earlier somewhere between 1 and 3 elements

I have:
Pharo12
Ubuntu 22.04
Intel 1280P
32 GB DDR4

**Comment by tesonep** [comment]
@PalumboN @guillep do we want this on P10 or p12?

**Comment by guillep** [comment]
Using these primitives require changes in the pharo code too, so maybe Pharo12 is the best

**Comment by guillep** [comment]
Superseeded by https://github.com/pharo-project/pharo-vm/pull/759

**Pull request closed without merging**
