### PR TITLE
VM Debugger improvement with IR

### PR DESCRIPTION
**Pull request by QDucasse**
Improvement of the VM machine code debugger with the following changes:
- Automated refresh of the columns (no need to click to refresh)
- Added abstract instructions in a column on the left
- Clicking on an abstract instruction shows the corresponding machine code instruction(s)
- Clicking on a machine code instruction shows the corresponding affected register(s)

Note that the mc <-> registers highlights have been tried with ARMv8 and RISC-V but could be applied to any other ISA as long as the register aliases are correctly defined.

### CODE REVIEW

**Comment by tesonep** [comment]
Cool, this is so nice

**Review by tesonep — APPROVED** [review]

**Comment by guillep** [comment]
I've changed the base branch to Pharo X (and we should work in there in the future).
I'll check the conflict.

**Comment by guillep** [comment]
I have the feeling that we will need to manually test after the merge :/. I've made some non-obvious merges.

**Comment by guillep** [comment]
I confirm this is working on the latest version.

imagen

I will test with a more complex method IR and push it if ok!

**Comment by guillep** [comment]
It seems that 
 - we have the stack and and registers panes duplicated
 - the IR <-> machine code mapping is not working in the UI

**Comment by guillep** [comment]
I've made a pass, this is how it looks now:

imagen

**Comment by guillep** [comment]
I'll merge it, thanks @QDucasse !!!!

**Pull request merged**
