### PR TITLE
Make instantiateClass more robust when the format is missing

### PR DESCRIPTION
**Pull request by privat**
Calling `primitiveNew` (`basicNew` in the image parlance) on a an object without a 3rd instance variable (where the format is expected to be) fail with randomly "not enough memory" or "bad receiver" (or can unlikely success) as the non existent 3rd slot is blindly read, thus garbage memory is misinterpreted.

In debug mode some assertions catch the issue, but it's not enough as the VM should try to be robust and consistent in case of wrong user data even in release mode.

The PR add a check of the existence of the format before accessing it and set the primitive fail accordingly.

It also does a small refactor of the related code so that the failure numbers are set at the same place.
Previously, precise error code set by `SpurMemoryManager >> instantiateClass:` (&cie) might have been overwrote by `InterpreterPrimitives >> primitiveNew` (&cie).

Note: I only check that the format exists, and not that it is a valid integer. Now writing the cover letter I think I should have done that. What do you think?

### CODE REVIEW

**Review by guillep — APPROVED** [review]
Good, but what happens if the instantiated class does not have instance variables at all? :D

**Comment by privat** [comment]
The tests use a receiver with 0 instance variables. But that raises the question about various Oop form like tagged integer or forward references. I will check that.

**Comment by privat** [comment]
Improved the PR to handle non integer format. I introduce `SpurMemoryManager>>#formatOfClassSafe:` to make the code cleaner. Also added more tests.

Note: what is happening with the CI? the previous pipeline is still pending :/

**Review by guillep — APPROVED** [review]
Thanks!

**Comment by privat** [comment]
There seems to be some CI issue, did you merge to soon?

**Comment by guillep** [comment]
Yes, I did it too fast. Let me revert and relaunch the CI.

**Pull request merged**
