### PR TITLE
Adding the missing tty.c file in the packaging.

### PR DESCRIPTION
**Pull request by tesonep**
We were missing the tty.c file, so it was not generating a valid package

### CODE REVIEW

**Comment by jacereda** [comment]
I guess this deserves a new release? Tried packaging it for Guix and faced this.

**Comment by guillep** [comment]
Certainly, last week our CI was not in a good shape, I think this will happen early this week.

**Comment by guillep** [comment]
Release 10.2.1 is ready (https://github.com/pharo-project/pharo-vm/pull/773).
I just checked and the artifacts were correctly uploaded to the file server.

You may test :)

**Comment by jacereda** [comment]
Built fine, thanks. Still working on the install phase though.

**Pull request merged**
